import { FaSistrix } from "react-icons/fa";
import { supabase } from "../../utils/supabase";
import Layout from "../../layout/layout";
import React from "react";
import Head from "next/head";
import formateDate from "../../functions/formatDate";

export default function Article({ article, article2 }) {
	const createdDate = formateDate(article.created_at);
	console.log(article2);
	return (
		<>
			<Head>
				<title>Blog</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<div id="top" className="pt-20">
					<div className="mx-auto bg-slate-900 w-full flex justify-center py-10">
						<div className="relative flex gap items-center max-w-sm w-full h-12 rounded-3xl focus-within:shadow-lg  overflow-hidden">
							<button className="grid place-items-center h-full w-12 text-gray-300 bg-white">
								<FaSistrix size={23} />
							</button>

							<input
								className="peer h-full w-full outline-none bg-white text-black text-md
						 		font-semibold pl-3"
								type="text"
								id="value"
								placeholder="Search something..."
							/>
						</div>
					</div>
				</div>
				<div className="container-article">
					<div className="article-div">
						<div className="author-left">
							<img
								src="https://minimaltoolkit.com/images/randomdata/female/97.jpg"
								className="rounded-sm object-cover"
								width="50px"
								height="50px"
								layout="responsive"
							/>
							<div className="flex column ml10 infos-author">
								<span>{article.name_author}</span>
								<span>{createdDate}</span>
							</div>
						</div>
						<div className="article-img">
							<img src={article.imageUrl} layout="responsive" />
						</div>
						<div className="article-itself">
							<h1>{article.title}</h1>
							<h2>{article.description}</h2>
							<div className="article-section">
								<p>{article.body}</p>
							</div>
						</div>
					</div>
					<div className="user-div">
						<div className="mb50">
							<div className="user-right-img">
								<img
									src="https://minimaltoolkit.com/images/randomdata/female/97.jpg"
									layout="responsive"
								/>
								<span className="ml20">{article.name_author}</span>
							</div>
							<div className="mt20">{article.description_author}</div>
						</div>
						<span>Découvrir plus</span>
						{article2.map((article) => (
							<div
								key={article.id}
								className="other-post flex space-between mt30"
							>
								<div className="col-9-sm">
									<div className="flex gap items-center">
										<img
											src={article.avatar_author}
											className="rounded-sm object-cover border-radius"
											width="30px"
											height="30px"
											layout="responsive"
										/>
										<small>{article.name_author}</small>
									</div>
									<h3>{article.description}</h3>
								</div>
								<div>
									<img
										src={article.imageUrl}
										className="rounded-sm object-cover"
										width="100px"
										height="100px"
										layout="responsive"
									/>
								</div>
							</div>
						))}
					</div>
				</div>
			</Layout>
		</>
	);
}

export async function getServerSideProps({ params }) {
	const { data: article, error } = await supabase
		.from("articles_view")
		.select("*")
		.eq("id", params.article)
		.single();

	const { data: article2, error2 } = await supabase
		.from("articles_view")
		.select("*")
		.order("created_at", { ascending: false })
		.limit(2);

	if (error || error2) {
		throw new Error(error);
	}

	return {
		props: {
			article,
			article2,
		},
	};
}
