import React from "react";
import Head from "next/head";
import Accueil from "../components/Accueil";
export default function Home() {
	return (
		<div>
			<Head>
				<title>Blog</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="w-full h-screen text-center">
				<div className=" w-full mx-auto flex justify-center">
					<div className="w-full h-10 bg-white p-10 ">
						<p className="font-semibold text-2xl ">Notre blog</p>
						<p className="my-2 text-lg">
							Bonjour, nous sommes Abessolo et Affadjene, étudiants à
							l'ECE-Paris, Nous vous présentons notre blog!
						</p>
					</div>
				</div>
				<div className="w-full h-3/4 flex items-center justify-center">
					<h2 className="">In progress...</h2>
				</div>
				<div className="info">
					<div className="Rova">
						<div className="photo"></div>
						<div className="info"></div>
					</div>
					<div className="Navil">
						<div className="photo"></div>
						<div className="info"></div>
					</div>
				</div>
			</div>
		</div>
	);
}
