import { supabase } from "../../../utils/supabase";
import Layout from "../../../layout/layout";
import React from "react";
import Head from "next/head";
import ArticleForm from "../../../components/ArticleForm/ArticleForm";

export default function Post() {
	async function handleSubmit(event) {
		event.preventDefault();

		const title = event.target.title.value;
		const description = event.target.description.value;
		const content = event.target.content.value;
		const imageUrl = event.target.url.value;

		const body = {
			title,
			body: content,
			description,
			imageUrl,
			author: "07bf408c-a0c9-473e-8f9e-48a8f66c1ddb", // auth.uid() @ToReplace
		};
		const { error } = await supabase.from("articles").insert(body);

		if (error) {
			console.log("Oups ! ", error.message);
		}
	}

	return (
		<>
			<Head>
				<title>Blog</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<ArticleForm handleSubmit={handleSubmit} />
			</Layout>
		</>
	);
}
